# Generated by Django 4.2.10 on 2024-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_core", "0002_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="is_shown",
            field=models.BooleanField(default=True),
        ),
    ]
