# Generated by Django 4.2.10 on 2024-02-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_core", "0003_friend_is_shown"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friend",
            options={"ordering": ["display_name"]},
        ),
    ]
