# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' python linting"
        entry: ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' python formatting"
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true
