name: container-image
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  schedule:
    - cron: "@weekly"

jobs:
  build-image:
    runs-on: alpine-latest
    container:
      image: ghcr.io/osscontainertools/kaniko:alpine
    steps:
      - name: Install required system packages
        run: apk add --no-cache nodejs
      
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Build Container
        env:
          KANIKO_NO_PUSH: ${{ forgejo.ref_name != 'main' }}
          KANIKO_GIT_HANSE_DE_USER: lilly
          KANIKO_GIT_HANSE_DE_PASSWORD: ${{ secrets.HANSE_PACKAGES_ACCESS }}
        run: /kaniko/executor
          --dockerfile="${{forgejo.workspace }}/dev/Containerfile"
          --context="dir://${{ forgejo.workspace }}"
          --destination=git.hanse.de/${{ forgejo.repository }}:latest
          --no-push-cache
          --credential-helpers=env
          --annotation=org.opencontainers.image.title="lillys homepage"
          --annotation=org.opencontainers.image.url=${{ forgejo.server_url }}/${{ forgejo.repository }}
          --annotation=org.opencontainers.image.source=${{ forgejo.server_url }}/${{ forgejo.repository }}
          --annotation=org.opencontainers.image.revision=${{ forgejo.sha }}
          --annotation=org.opencontainers.image.licenses=AGPL-3.0-or-later
