FROM docker.io/alpine:3.22 AS base

ARG APP_UID=10000
ARG APP_GID=10000
ENV UV_PROJECT=/usr/local/src/homepage/backend
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV VIRTUAL_ENV=/usr/local/share/homepage/venv/
ENV PATH=$VIRTUAL_ENV/bin:$PATH
ENV HOMEPAGE_STATIC_ROOT=/var/www/homepage/backend-static/
WORKDIR /usr/local/src/homepage/

RUN apk add --no-cache uv nginx python3 tzdata pnpm
RUN addgroup -g $APP_GID homepage &&\
    adduser -h /usr/local/src/homepage -u $APP_UID -G homepage -D homepage &&\
    mkdir -p /var/lib/nginx/ /var/log/nginx/ /run/nginx/ /var/www/homepage/ /usr/local/share/homepage/ /usr/local/src/homepage/frontend/ /usr/local/src/homepage/backend/ &&\
    chown -R homepage:homepage /var/lib/nginx/ /var/log/nginx/ /run/nginx /var/www/homepage/ /usr/local/share/homepage/ /usr/local/src/homepage/


FROM base AS deps
USER homepage
RUN --mount=type=cache,uid=$APP_UID,gid=$APP_GID,target=/usr/local/src/homepage/.cache/uv \
    --mount=type=bind,source=backend/,target=/usr/local/src/homepage/backend/ \
    cd backend &&\
    uv venv $VIRTUAL_ENV &&\
    uv sync --active --frozen --no-install-project --no-editable
RUN --mount=type=bind,source=frontend/package.json,target=/usr/local/src/homepage/frontend/package.json \
    --mount=type=bind,source=frontend/pnpm-lock.yaml,target=/usr/local/src/homepage/frontend/pnpm-lock.yaml \
    cd frontend &&\
    pnpm install --frozen-lockfile --shamefully-hoist --store-dir /usr/local/share/homepage/pnpm-store



FROM deps AS final
ENV NUXT_BACKEND_URL=http://localhost:8000
ADD backend/ /usr/local/src/homepage/backend/
RUN cd backend &&\
    uv sync --active --frozen
RUN export HOMEPAGE_SECRET_KEY=django-insecure \
           HOMEPAGE_BASE_URI=http://invalid.invalid \
           HOMEPAGE_DB_URL=sqlite:///:memory: \
           HOMEPAGE_OPENID_ISSUER=https://invalid.invalid \
           HOMEPAGE_OPENID_CLIENT_ID=invalid \
           HOMEPAGE_OPENID_CLIENT_SECRET=invalid &&\
    ./backend/manage.py collectstatic
ADD frontend/ /usr/local/src/homepage/frontend/
RUN cd frontend &&\
    pnpm run build

ADD dev/prod.nginx.conf /etc/nginx/http.d/default.conf
ADD dev/cmd.sh /usr/local/bin/cmd.sh
CMD [ "/usr/local/bin/cmd.sh" ]
ENV HOMEPAGE_STATIC_ROOT=/var/www/homepage/backend-static/
EXPOSE 80/tcp
