# Generated by Django 4.2.10 on 2024-02-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
