# Generated by Django 5.2.4 on 2025-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webmention",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "own_path", "href", "page_hash", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("own_path", models.CharField(max_length=256)),
                ("href", models.CharField(max_length=256)),
                ("page_hash", models.BinaryField()),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("webmention_sent", models.BooleanField(default=False)),
            ],
        ),
    ]
