# Generated by Django 5.2.4 on 2025-07-28 19:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundWebmentionContent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="Webmention",
            new_name="OutboundWebmention",
        ),
        migrations.CreateModel(
            name="InboundWebmention",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("own_path", models.CharField(max_length=256)),
                ("source", models.CharField(max_length=256)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.inboundwebmentioncontent",
                    ),
                ),
            ],
        ),
    ]
