# Generated by Django 6.0.5 on 2026-06-19 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_inboundwebmentioncontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('public_handle', models.CharField(blank=True, max_length=32)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('content', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
