depends_on: [ test ]

steps:
  - name: build container image
    image: docker.io/woodpeckerci/plugin-kaniko
    settings:
      registry: git.lly.sh
      repo: ${CI_REPO}
      username: lilly
      password:
        from_secret: FORGEJO_PACKAGES_ACCESS

#  - name: build container image
#    when:
#      - event: push
#      - event: cron
#      - event: manual
#    image: quay.io/containers/podman
#    privileged: true
#    commands:
#      - podman build -f dev/Containerfile . -t homepage
#      - podman save homepage -o container.tar.gz
#
#  - name: publish container image
#    when:
#      - event: manual
#        branch: main
#      - event: push
#        branch: main
#      - event: cron
#        cron: periodic-rebuild
#    image: quay.io/containers/skopeo
#    environment:
#      FORGEJO_PACKAGES_ACCESS:
#        from_secret: FORGEJO_PACKAGES_ACCESS
#      GITHUB_PACKAGES_ACCESS:
#        from_secret: GITHUB_PACKAGES_ACCESS
#    commands:
#      - skopeo copy --dest-username lilly --dest-password $FORGEJO_PACKAGES_ACCESS docker-archive:container.tar.gz docker://git.lly.sh/lilly/homepage
#      - skopeo copy --dest-username lilioid --dest-password $GITHUB_PACKAGES_ACCESS docker-archive:container.tar.gz docker://ghcr.io/lilioid/homepage
