steps:
  - name: check-pre-commit
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: docker.io/nixos/nix
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
    commands:
      - . <(nix --extra-experimental-features "nix-command flakes" print-dev-env .)
      - pre-commit run --show-diff-on-failure --all-files

  - name: test-app
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: docker.io/nixos/nix
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
      UV_LINK_MODE: symlink
    commands:
      - . <(nix --extra-experimental-features "nix-command flakes" print-dev-env .)
      - uv venv
      - uv pip install -e .[dev]
      - .venv/bin/pytest
