steps:
  - name: check-pre-commit
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: docker.io/nixos/nix
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 2Gi
    commands:
      - . <(nix --extra-experimental-features "nix-command flakes" print-dev-env .)
      - pre-commit run --show-diff-on-failure --all-files
