steps:
  - name: check-pre-commit
    depends_on: []
    when:
      - event: push
      - event: cron
      - event: manual
    image: docker.io/nixos/nix
    volumes:
      - woodpecker-cache:/woodpecker/src/cache
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 500Mi
    environment:
      XDG_CACHE_HOME: /woodpecker/src/cache
    commands:
      - . <(nix --extra-experimental-features "nix-command flakes" print-dev-env .)
      - pre-commit run --show-diff-on-failure --all-files
